name: Build LaTeX PDF

on:
  push:
    branches: [ "tex_tmp" ]
  pull_request:
    branches: [ "tex_tmp" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: tex/
      
      - name: Rename PDF
        run: |
          old_path="tex/main.pdf"
          new_name="Hybrid_UAV_Waypoint_Tracking.pdf"
          mv "$old_path" "$new_name"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hybrid_UAV_Waypoint_Tracking_pdf
          path: Hybrid_UAV_Waypoint_Tracking.pdf