name: "Maintain TODO Issues"
on:
  push:
    branches:
      - main
jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "TODO to Issue"
        uses: alstr/todo-to-issue-action@v4
        with:
          INSERT_ISSUE_URL: true
          CLOSE_ISSUES: true
          AUTO_PNAME: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}